### ISSUE TITLE
Cache ci dependencies

### ISSUE THREAD

**Issue by jespertheend** [rendajs/Renda#2]
We can cache both the results from deno (https://github.com/denoland/setup-deno/issues/31#issuecomment-1209782606) as well as the downloaded types in `.denoTypes` and the downloaded `npm_packages`. We could also cache `node_modules` but the plan is to get rid of these eventually so that's not a priority.

**Comment by digitaldesigndj** [comment]
Thanks for the example. Mine even seems to cache the chrome install for puppeteer automatically!

For the others like me
```yaml

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DENO_DIR: deno_dir
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup .env secrets file
        run: echo $ENV_GITHUB_ACTIONS | base64 -d > .env
        env:
          ENV_GITHUB_ACTIONS: ${{ secrets.ENV_GITHUB_ACTIONS }}

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.25.1
      
      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          # The Chrome install gets cached too
          # import_map.json as key doesnt always work, 
          # if is not enough, we can add more files here.
          key: denoDeps-${{ hashFiles('import_map.json') }}
          path: ${{ env.DENO_DIR }}

      - name: Install Chromium for Puppeteer
        run: PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts

      # Verify the use of 'deno fmt' on each commit.
      - name: Verify formatting
        run: deno fmt --check
```
